plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'com.mystic'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

javafx {
    version = '17.0.6'
    modules = ['javafx.controls', 'javafx.graphics']
}

application {
    mainClass = 'com.mystic.chessultima.ui.ChessUltimaApp'
}

run {
    // Allow standard input if ever needed and nicer logging
    standardInput = System.in
}
